version: '3.7'

services:
  web:
    build: .
    command:  >
      bash -c "
        python app/manage.py makemigrations &&
        python app/manage.py migrate &&
        python app/manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  postgres_data: