# Generated by Django 3.0.5 on 2020-04-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txcovid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accelerometer',
            name='study_name',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='study_name',
        ),
        migrations.RemoveField(
            model_name='identifier',
            name='study_name',
        ),
        migrations.RemoveField(
            model_name='proximity',
            name='study_name',
        ),
        migrations.RemoveField(
            model_name='reachability',
            name='study_name',
        ),
        migrations.RemoveField(
            model_name='screentime',
            name='study_name',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='study_name',
        ),
        migrations.AlterField(
            model_name='trackrecord',
            name='track_date',
            field=models.DateField(unique=True),
        ),
    ]
